# Generated by Django 5.0 on 2023-12-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
